POST http://localhost:6364/videos
Content-Type: application/json

{
    "title": "video node",
    "description": "Este é o video 01",
    "duration": 180
}


###

GET http://localhost:6364/videos?search=

###

PUT  http://localhost:6364/videos/
Content-Type: application/json

{
    "title": "EDITAR TITULO",
    "description": "EDITAR DESCRIPTION",
    "duration": 180
}
###

DELETE  http://localhost:6364/videos/
